"use client";
import "../styles/globals.scss";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJs Task Project",
  description: "Generated by tajul islam refath",
};

export default function RootLayout({ children, pageProps }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
